version: "3.8"

services:
    #######################################
    # Portfolio container
    #######################################
    portfolio:
        container_name: portfolio
        image: ghcr.io/jannismilz/jannismilz.com:v1
        networks:
            - personal
        restart: unless-stopped

networks:
    personal:
        external: true
