version: "3.8"

services:
    #######################################
    # Portfolio container
    #######################################
    jannismilz:
        container_name: jannismilz
        image: ghcr.io/jannismilz/jannismilz.com:latest
        networks:
            - personal
        restart: unless-stopped

networks:
    personal:
        external: true
