version: "3.8"

services:
    #######################################
    # Portfolio container
    #######################################
    portfolio:
        container_name: portfolio
        image: ghcr.io/jannismilz/portfolio:v1.1
        networks:
            - personal
        restart: unless-stopped

networks:
    personal:
        external: true
